[package]
name = "evm-asm"
description = "Compile-time EVM bytecode assembly macro."
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
repository = "https://github.com/makcandrov/evm-asm"
homepage = "https://github.com/makcandrov/evm-asm"
documentation = "https://docs.rs/evm-asm"
license = "MIT OR Apache-2.0"
keywords = ["evm", "asm", "ethereum", "bytecode", "proc-macro"]

[lib]
proc-macro = true

[features]
default = []
opcode-docs = []

[dependencies]
proc-macro2 = "1"
quote = "1"
ruint = { version = "1", default-features = false }
syn = { version = "3", features = ["full"] }

[dev-dependencies]
proc-macro2 = { version = "1", features = ["span-locations"] }

[package.metadata.docs.rs]
all-features = true
