// Legacy EVM instruction encodings through the Amsterdam execution-specs branch:
// https://github.com/ethereum/execution-specs/blob/forks/amsterdam/src/ethereum/forks/amsterdam/vm/instructions/__init__.py
pub(crate) fn lookup(name: &str) -> Option<u8> {
    let opcode = match name {
        "stop" => 0x00,
        "add" => 0x01,
        "mul" => 0x02,
        "sub" => 0x03,
        "div" => 0x04,
        "sdiv" => 0x05,
        "mod" => 0x06,
        "smod" => 0x07,
        "addmod" => 0x08,
        "mulmod" => 0x09,
        "exp" => 0x0a,
        "signextend" => 0x0b,
        "lt" => 0x10,
        "gt" => 0x11,
        "slt" => 0x12,
        "sgt" => 0x13,
        "eq" => 0x14,
        "iszero" => 0x15,
        "and" => 0x16,
        "or" => 0x17,
        "xor" => 0x18,
        "not" => 0x19,
        "byte" => 0x1a,
        "shl" => 0x1b,
        "shr" => 0x1c,
        "sar" => 0x1d,
        "clz" => 0x1e,
        "keccak256" | "keccak" | "sha3" => 0x20,
        "address" => 0x30,
        "balance" => 0x31,
        "origin" => 0x32,
        "caller" => 0x33,
        "callvalue" => 0x34,
        "calldataload" => 0x35,
        "calldatasize" => 0x36,
        "calldatacopy" => 0x37,
        "codesize" => 0x38,
        "codecopy" => 0x39,
        "gasprice" => 0x3a,
        "extcodesize" => 0x3b,
        "extcodecopy" => 0x3c,
        "returndatasize" => 0x3d,
        "returndatacopy" => 0x3e,
        "extcodehash" => 0x3f,
        "blockhash" => 0x40,
        "coinbase" => 0x41,
        "timestamp" => 0x42,
        "number" => 0x43,
        "prevrandao" | "difficulty" => 0x44,
        "gaslimit" => 0x45,
        "chainid" => 0x46,
        "selfbalance" => 0x47,
        "basefee" => 0x48,
        "blobhash" => 0x49,
        "blobbasefee" => 0x4a,
        "slotnum" => 0x4b,
        "pop" => 0x50,
        "mload" => 0x51,
        "mstore" => 0x52,
        "mstore8" => 0x53,
        "sload" => 0x54,
        "sstore" => 0x55,
        "jump" => 0x56,
        "jumpi" => 0x57,
        "pc" => 0x58,
        "msize" => 0x59,
        "gas" => 0x5a,
        "jumpdest" => 0x5b,
        "tload" => 0x5c,
        "tstore" => 0x5d,
        "mcopy" => 0x5e,
        "dupn" => 0xe6,
        "swapn" => 0xe7,
        "exchange" => 0xe8,
        "create" => 0xf0,
        "call" => 0xf1,
        "callcode" => 0xf2,
        "return" => 0xf3,
        "delegatecall" => 0xf4,
        "create2" => 0xf5,
        "staticcall" => 0xfa,
        "revert" => 0xfd,
        "invalid" => 0xfe,
        "selfdestruct" | "suicide" => 0xff,
        _ => {
            for (prefix, min, max, base) in [
                ("push", 0, 32, 0x5f),
                ("dup", 1, 16, 0x7f),
                ("swap", 1, 16, 0x8f),
                ("log", 0, 4, 0xa0),
            ] {
                if let Some(suffix) = name.strip_prefix(prefix) {
                    let index = suffix.parse::<u8>().ok()?;
                    // Reject noncanonical spellings such as `push01`.
                    return ((min..=max).contains(&index) && suffix == index.to_string())
                        .then(|| base + index);
                }
            }
            return None;
        }
    };
    Some(opcode)
}
